cmake_minimum_required(VERSION 3.10)
project(cqueue_demo)

add_executable(cqueue_demo main.cpp)
set_target_properties(cqueue_demo PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED ON)
target_include_directories(cqueue_demo PUBLIC ${CMAKE_SOURCE_DIR}/3rd/include)

# Install module-local config/docs
set(MODULE_BUILD_DIR ${CMAKE_BINARY_DIR})
if(DEFINED MODULE_COLLECTION)
    set(MODULE_BUILD_DIR ${MODULE_BUILD_DIR}/${MODULE_COLLECTION})
endif()
if(DEFINED MODULE_NAME)
    set(MODULE_BUILD_DIR ${MODULE_BUILD_DIR}/${MODULE_NAME})
elseif(DEFINED PROJECT_NAME)
    set(MODULE_BUILD_DIR ${MODULE_BUILD_DIR}/${PROJECT_NAME})
endif()
set(OUTPUT_DIR ${MODULE_BUILD_DIR})
if(FLAT_MODE)
    set(INSTALL_ETC_DIR ${OUTPUT_DIR})
    set(INSTALL_DOC_DIR ${OUTPUT_DIR})
else()
    set(INSTALL_ETC_DIR ${OUTPUT_DIR}/etc)
    set(INSTALL_DOC_DIR ${OUTPUT_DIR}/doc)
endif()
file(GLOB CFG_FILES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/etc/*)
if(CFG_FILES)
    file(INSTALL ${CFG_FILES} DESTINATION ${INSTALL_ETC_DIR})
endif()
file(GLOB DOC_FILES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/doc/*)
if(DOC_FILES)
    file(INSTALL ${DOC_FILES} DESTINATION ${INSTALL_DOC_DIR})
endif()
